FROM osrm/osrm-backend

# Set the working directory inside the container
WORKDIR /data

# Copy your local OSRM data into the container's /data directory
# Assuming the .osrm files are stored in the 'osrm-data' directory
# COPY ./osrm-data /data
COPY ./profiles/bicycle-hard.lua /opt/
# COPY ./osm-files/osm-data.osm /data/
# Expose the OSRM routing engine port (5000)
# EXPOSE 5002