version: '3'
services:
  osrm-easy:
    build:
      context: .  # The build context, usually the current directory
      dockerfile: Dockerfile-easy  # Specify your custom Dockerfile name
    # command: tail -f /dev/null  # Keeps the container running indefinitely
    command: osrm-routed /data/osm-data.osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data-easy:/data

  osrm-medium:
    build:
      context: .  # The build context, usually the current directory
      dockerfile: Dockerfile-medium  # Specify your custom Dockerfile name
    # command: tail -f /dev/null  # Keeps the container running indefinitely
    command: osrm-routed /data/osm-data.osrm
    ports:
      - "5001:5000"
    volumes:
      - ./osrm-data-medium:/data
  
  osrm-hard:
    build:
      context: .  # The build context, usually the current directory
      dockerfile: Dockerfile-hard  # Specify your custom Dockerfile name
    # command: tail -f /dev/null  # Keeps the container running indefinitely
    command: osrm-routed /data/osm-data.osrm
    ports:
      - "5002:5000"
    volumes:
      - ./osrm-data-hard:/data
